name: CI + CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: sh myscript.sh
    
  DeployDevJumpServer:
    name: Deploy to Dev-Jump Server
    if: github.event_name == 'push'
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: DevJumpServer
      url: 'http://www.google.com'
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: echo I am deploying! 

  DeployDev:
    name: Deploy to Dev 
    needs: [DeployDevJumpServer]
    runs-on: ubuntu-latest
    environment: 
      name: Development
      url: 'http://www.google.com'
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: echo I am deploying! 
    
  DeployStaging:
    name: Deploy to Staging 
    if: github.event.ref == 'refs/heads/main'
    needs: [DeployDev]
    runs-on: ubuntu-latest
    environment: 
      name: JumpServer
      url: 'http://test.myapp.com'
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
       # run: echo I am deploying! 
        run: sh myscript.sh
            
  DeployProd:
    name: Deploy to Production 
    needs: [DeployStaging]
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: 'http://www.myapp.com'
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: echo I am deploying! 
    
