name: Run Spring Project Using Docker
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name : Docker Build
      run : |
        echo "Vickey\$123" | sudo -S su -c '
        docker build -t docker_action Dockerfile

    - name : Docker Images
      run : |
         echo "Vickey\$123" | sudo -S su -c ' 
         docker images

    - name : Docker Run
      run : |
        echo "Vickey\$123" | sudo -S su -c '
        docker run -d docker_action

      
