name: Run Spring Project Using Docker
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name : Docker Build
      run : echo  '${{ secrets.SUDO_PASSWORD }}'| sudo -S docker build -t my_first_image /app/Dockerfile

    - name : Docker Images
      run : echo  '${{ secrets.SUDO_PASSWORD }}'| sudo -S docker images

    - name : Docker Run
      run : echo  '${{ secrets.SUDO_PASSWORD }}'| sudo -S docker run my_first_image

      
