name: Run Spring Project Using Docker
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name : Docker Build
      run : |
        cd /home/vvdn/gitAction/git_repository/DockerAction/
        echo  '${{ secrets.SUDO_PASSWORD }}'| sudo -S docker build -t my_first_image .

    - name : Docker Images
      run : echo  '${{ secrets.SUDO_PASSWORD }}'| sudo -S docker images

    - name : Docker Run
      run : echo  '${{ secrets.SUDO_PASSWORD }}'| sudo -S docker run -d my_first_image

      
