name: Run Spring Project Using Docker
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name : Docker Build
      run : docker build -t docker_action Dockerfile

    - name : Docker Images
      run : docker images

    - name : Docker Run
      run : docker run -d docker_action

      
